### PR TITLE
Check if Fortran interfaces are enabled

### PR DESCRIPTION
**Pull request by gardner48**
When using an existing AMReX install, the top level CMake always calls `enable_language(Fortran)` so the Fortran compiler is found even if the Fortran interfaces are disabled.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
@ax3l Did something change in pyamrex?

**Comment by ax3l** [comment]
Ah, this is a breaking change from AMReX from earlier this week. I fixed it today: https://github.com/AMReX-Codes/pyamrex/pull/324

**Review by ax3l — APPROVED** [review]
Thanks! :)

**Comment by ax3l** [comment]
That macOS error looks familiar, some breakage in homebrew:
```
ld: warning: directory not found for option '-L/usr/local/opt/gcc/lib/gcc/current'
ld: file not found: @rpath/libquadmath.0.dylib for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Pull request merged**
