### PR TITLE
Reorganize

### PR DESCRIPTION
**Pull request by etpalmer63**
This PR reorganizes the Tutorials into two categories, tentatively named:  "Guided Tutorials" and "Code Examples".  I'm putting this up as work-in-progress in the hope to incorporate feedback from others.

If you want to see the html, pull my branch and go to `amrex-tutorials/Docs` and type `make`. Then use your web browser to navigate to `amrex-tutorials/Docs/build/html/index.html`.

### CODE REVIEW

**Comment by etpalmer63** [comment]
Sorry this PR is a bit large. It does the following: 

- sorts the tutorials into two directories, ExampleCodes and GuidedTutorials. I also copied over the folders from the ECP-tutorials and the ATPESC examples.  For these files I didn't make any changes (despite what github says). Some files temporarily exist in both places for the moment. 
- updates the file paths in the rst files to reflect the new locations and removed the `Tutorials/` in the titles.
- redoes the `index.rst` file and adds a page to direct people to the tutorials and examples.

**Comment by etpalmer63** [comment]
Here are several things I hope this PR does:
1. Maintain all the functionality of the current content. That is all the current tutorials have been moved to ExampleCodes, and they build in the same way they did previously. -- I checked this by building with several of the available options. A quick way to check I found was to build with as many flags as possible, and use `find` to ensure the executable files were made. 
2. Enable Gitpod functionality for the `HeatEquation_Simple` tutorial. -- I checked this by running GitPod on this current branch. 
3. Uses new `CMakeLists.txt` files to compile the Guided Tutorials. The new CMake files are completely independent of the directory structure and work both with and without separately installed AMReX. 
4. New Guided Tutorials can also be built with GNU Make. -- Tested each one with defaults individually.

**Comment by etpalmer63** [comment]
Now passes the current CI test suite.

**Comment by atmyers** [comment]
Thank you for doing this. Looks good to me!

**Review by atmyers — APPROVED** [review]

**Pull request merged**
