### PR TITLE
change to test some functionality

### PR DESCRIPTION
**Pull request by etpalmer63**
Try typing "Do.Tests" to initiate tests on this repo.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
Do.Tests

**Comment by WeiqunZhang** [comment]
I intentionally inserted a number of spaces before and after `Do.Tests`.  Would this comment trigger testing too?

**Comment by etpalmer63** [comment]
Looks like that one didn't work

**Comment by WeiqunZhang** [comment]
Do.Tests   How after space after it?

**Comment by etpalmer63** [comment]
I think the comment needs to be "Do.Tests" and nothing else, but let me double check

**Comment by WeiqunZhang** [comment]
What about new lines by `Enter`?

**Comment by WeiqunZhang** [comment]
So what exactly is the match syntax?

**Comment by WeiqunZhang** [comment]
Do.Tests

**Comment by etpalmer63** [comment]
The comment needs to be exactly "Do.Tests" and nothing else  --> `github.event.comment.body == env.TRIGGER_STRING`

**Comment by WeiqunZhang** [comment]
Do.Tests

**Comment by WeiqunZhang** [comment]
Seems to work

**Comment by etpalmer63** [comment]
From here it's taking about 20 mins to complete the CI.

**Comment by etpalmer63** [comment]
I have concerns about how it could break .. I use the PR comment to find the branch, so if there are a lot of comments at once, I'm worried it might grab the wrong one. I'm also concerned about triggering it multiple times before it finishes the previous task. 

I have been looking for some example bots to see how they handle these things but haven't found a good example yet.

**Comment by etpalmer63** [comment]
HeatEquation -- Cori Compile Success

**Comment by etpalmer63** [comment]
CNS_SOD -- Cori Compile Success

**Comment by etpalmer63** [comment]
CNS_RT -- Cori Compile Success

**Comment by asalmgren** [comment]
I'd also like to comment on this PR ...

**Comment by asalmgren** [comment]
Do.Tests

**Comment by etpalmer63** [comment]
Do.Tests

**Comment by etpalmer63** [comment]
HeatEquation -- Cori Compile Success

**Comment by etpalmer63** [comment]
CNS_SOD -- Cori Compile Success

**Comment by etpalmer63** [comment]
CNS_RT -- Cori Compile Success

**Comment by etpalmer63** [comment]
Test

**Comment by etpalmer63** [comment]
Test

**Comment by atmyers** [comment]
Do.Tests

**Comment by etpalmer63** [comment]
HeatEquation -- Cori Compile Success

**Comment by etpalmer63** [comment]
Do.Tests

**Comment by etpalmer63** [comment]
CNS_SOD -- Cori Compile Success

**Comment by etpalmer63** [comment]
HeatEquation -- Cori Compile Success

**Comment by etpalmer63** [comment]
CNS_RT -- Cori Compile Success

**Comment by jmsexton03** [comment]
Do.Tests

**Comment by etpalmer63** [comment]
HeatEquation -- Cori Compile Success

**Comment by etpalmer63** [comment]
CNS_SOD -- Cori Compile Success

**Comment by etpalmer63** [comment]
CNS_RT -- Cori Compile Success

**Pull request closed without merging**
